// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7WFuQed2KQHuJY0MvN3eh1YbXsARzlZI',
    appId: '1:755600674475:web:a982ad1a34ca7899c631ee',
    messagingSenderId: '755600674475',
    projectId: 'login-signup-sdp',
    authDomain: 'login-signup-sdp.firebaseapp.com',
    storageBucket: 'login-signup-sdp.appspot.com',
    measurementId: 'G-2YF18TBCJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATNRzMQMnP_h6yqAmsO6Sd035cnxp5IAs',
    appId: '1:755600674475:android:f634f34df99965efc631ee',
    messagingSenderId: '755600674475',
    projectId: 'login-signup-sdp',
    storageBucket: 'login-signup-sdp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0pWmbKvP5O4o-uKegEV36a_FvYKa92kY',
    appId: '1:755600674475:ios:41ebc66e67bec908c631ee',
    messagingSenderId: '755600674475',
    projectId: 'login-signup-sdp',
    storageBucket: 'login-signup-sdp.appspot.com',
    iosBundleId: 'com.example.loginSignupSpeechText',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0pWmbKvP5O4o-uKegEV36a_FvYKa92kY',
    appId: '1:755600674475:ios:a59593c266f0cddbc631ee',
    messagingSenderId: '755600674475',
    projectId: 'login-signup-sdp',
    storageBucket: 'login-signup-sdp.appspot.com',
    iosBundleId: 'com.example.loginSignupSpeechText.RunnerTests',
  );
}
